export default [
    "Want to do something with that animal you just captured? You can use the shortcut 'last' on any animal-specific command to easily target the last animal in your collection.",
    "Animals give little rewards as they level up, with the amount of rewards given increasing as level does. Animals can start dropping extra captures at level 5!",
    "Prize balls have a pretty high upper limit for the rewards they can give. If a prize ball's reward is large enough to occur less than 1% of the time, the reward will be followed by a 'wow!'",
    "Want to view another player's collection, but don't want to ping them? Just copy their user ID and use that instead of their tag, it works exactly the same!",
    "Random animal encounters have a 1% chance to spawn anytime a message in the server is sent, but a random encounter can only occur every few minutes.",
    "Voting on bot lists don't all have the same cooldown period. Make sure to check the website to see exactly just how often you can vote and claim your rewards!",
    "There are semi-secret medals to collect for your Beastiary. You'll get a bronze medal once you've captured over 20% of all existing species, with more medals coming afterwards.",
    "When you release an animal, it rewards you with an amount of essence equal to double its level.",
    "Got a favorite animal that's not in The Beastiary? Suggest it in the `feedback` command, or better yet, submit it with the `submit` command!",
    "Something wrong with your player stats? Use the `refresh` command to refresh your data and potentially fix the problem, then report the bug with the `feedback` command.",
    "Want to quickly move an animal to the top of your collection? Using the `favorite` command does just that, it gives your animal a little emoji flare too.",
    "When releasing an animal, you have to type exactly 'yes' in order to confirm it. This was done to minimize potential accidental releases with a simple 'y' message.",
    "A species' token is hidden until you earn it, and you can never lose a token once you've gained it!",
    "Want more encounters waiting for you when you wake up in the morning? Upgrade your free encounter max stack with the `upgrade` command.",
    "Most commands that show your player-specific information can be used to view another player's information. Just follow the command with their tag or ID!",
    "Your top species is the species that you have the most essence in, and is listed proudly on your profile for everyone to see.",
    "Want a prettier color for your collection, crew, or profile? The embed color is determined by the first animal in those pages' respective lists. Favorite the animal with your preferred rarity color to spruce up your profile!",
    "The `alias` command shows you all the abbreviated versions of every command that exists, allowing you to do things like `encounter` easier (abbreviated simply to `e`).",
    "The `resets` command shows you a big list of all the time-constrained things in the game, and your remaining duration until you get more free things like encounters, captures, or xp boosts.",
    "While fishing, any message that contains the word 'reel' will be treated as a command to reel in your line. Be careful!",
    "Each species rarity tier is roughly twice as rare as the one coming before it. T2 is 2x as rare as T1, 4x as rare as T0, and so on.",
    "The greenland shark was placed in rarity tier 13 initially as a joke, but it just felt too right, so it stuck.",
    "When multiple people are capturing the same animal, the person who initiated the encounter (if capturing) has a statistical edge in the random selection process.",
    "Once you already have a species' token, it still tries to drop it again in the future. If it does, it will drop 5 of its species' essence instead of the token again.",
    "Is my prefix used by another bot? Specify me specifically by tagging me instead!",
    "You can select animals in your collection by their common name, but be sure to surround it with quotes if it has multiple words, and isn't the first argument in the command!",
    "If a command's argument is the last thing you type in the message, you most likely don't need to use quotes if it has multiple words.",
    "The daily pep reset occurs every day at 12am GMT. Set your clocks!",
    "A good fishing cast should take 5-10 minutes, but only if you're over the sweet spot. You know you're far away from the spot if fishing takes more than 20 minutes.",
    "You can buy multiple of one item from the shop by specifying its quantity, but you can't buy multiple upgrades at once.",
    "You can view other players' animals with the `animalinfo` command, but only if the animal you're looking for has a nickname.",
    "If there's a problem with your crew, or you just want to empty it out quickly, you can use the `crew` `clear` command.",
    "Tired of one of your animals' nicknames? Reset it by just using the `nickname` command, specifying the animal, but leaving the nickname field blank.",
    "You can trade animals for other animals or pep, but if you're feeling generous, you can just gift an animal to somebody with the `giveanimal` command.",
    "If you need more detailed information about a specific aspect of the game, it's probably in the `gameinfo` command. If it's not, let us know with the `feedback` command and it can be added.",
    "Premium players get 1 xp for each crew animal every time they send a message, but there are caps to prevent this from being abused with spam.",
    "Want a specific tip? Specify a tip number with this command to get exactly the one you want, or to cycle through all of them."
];