const gameConfig = {
    randomEncounterChanceOnMessage: 0.01,
    randomEncounterGuildCooldown: 120000,
    dailyCurrencyPeriod: 22 * 60 * 1000,
    freeEncounterPeriod: 1 * 60 * 1000,
    freeEncountersPerPeriod: 2,
    freeEncounterMaxStack: 5,
    freeCapturePeriod: 4 * 60 * 1000,
    freeCapturesPerPeriod: 1,
    tokenDropChance: 2500,
    freeXpBoostPeriod: 1 * 60 * 1000,
    freeXpBoostsPerPeriod: 1,
    freeXpBoostMaxStack: 3,
    xpPerBoost: 25,
    xpPerMessage: 1,
    xpPerEncounter: 5,
    xpPerCapture: 30,
    xpPerFish: 3,
    maxCrewSize: 2,
    animalCacheTimeout: 180000,
    playerGuildCacheTimeout: 180000,
    playerCacheTimeout: 180000,
    speciesCacheTimeout: 300000,
    gameObjectSaveDelay: 15000,
    patreonLink: "https://www.patreon.com/coolbrd",
    supportServerInviteLink: "https://discord.gg/875FPDdRQk"
};
export default gameConfig;